version: "3.3"
services:

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: athena
      MYSQL_USER: athena
      MYSQL_PASSWORD: athena
    networks:
      - athena
    ports:
      - "3306:3306"
    restart: always

  athena-monitor:
    container_name: athena-monitor
    image: athena/athena-monitor-linux-amd64:${BRANCH:-main}
    volumes:
      - ./creds.yaml:/etc/athena/main.yaml
      - ./athena-monitor.yaml:/etc/athena/monitor.yaml
      - ./athena-monitor-directories.yaml:/etc/athena/monitor-directories.yaml
      - ./tmp:/tmp/athena
    command: /athena-monitor --config /etc/athena/main.yaml --config /etc/athena/monitor.yaml --config /etc/athena/monitor-directories.yaml --log.level="debug"
    depends_on:
      - nats-streaming
      - db
    networks:
      - athena
    restart: always

  athena-processor:
    container_name: athena-processor
    image: athena/athena-processor-linux-amd64:${BRANCH:-main}
    volumes:
      - ./creds.yaml:/etc/athena/main.yaml
      - ./athena-processor.yaml:/etc/athena/processor.yaml
      - ./athena-processor-upload.yaml:/etc/athena/processor-upload.yaml
      - ./tmp:/tmp/athena
    command: /athena-processor --config /etc/athena/main.yaml --config /etc/athena/processor.yaml --config /etc/athena/processor-upload.yaml --log.level="debug"
    depends_on:
      - nats-streaming
      - db
    networks:
      - athena
    restart: always

  nats-streaming:
    container_name: nats-streaming
    image: nats-streaming
    ports:
      - '4222:4222'
      - '8223:8223'
      - 4222
    environment:
      - file
    networks:
      - athena
    restart: always

networks:
  athena:
    driver: bridge
