FROM ubuntu:22.04

LABEL maintainer="Canonical Sustaining Engineering <edward.hope-morley@canonical.com>"
LABEL org.opencontainers.image.description "Athena Monitor"

RUN apt-get update
RUN apt-get install --no-install-recommends --yes \
    iproute2 \
    iputils-ping
RUN apt-get update
RUN apt-get install --no-install-recommends --yes \
    default-mysql-client
