version: "3.3"
services:
#  salesforce:
#    container_name: salesforceapi
#    image: outofcoffee/imposter-sfdc
#    ports:
#      - 8080:8080
#    volumes:
#      - ./mocks:/opt/imposter/config
#    command: --configDir /opt/imposter/config --serverUrl http://localhost:8080
#
#  filescom:
#    container_name: filescomapi
#    image: filescom/files-mock-server:latest
#    networks:
#      - athena
#    restart: always

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: athena
      MYSQL_USER: athena
      MYSQL_PASSWORD: athena
    networks:
      - athena
    ports:
      - "3306:3306"

  athena-monitor:
    container_name: athena-monitor
    image: athena/athena-monitor-linux-amd64:${BRANCH:-main}
    volumes:
      - ./development-config.yaml:/etc/athena/main.yaml
    command: /athena-monitor --log.level="debug"
    depends_on:
      - nats-streaming
      - db
    networks:
      - athena
    restart: always

  athena-processor:
    container_name: athena-processor
    image: athena/athena-processor-linux-amd64:${BRANCH:-main}
    volumes:
      - ./development-config.yaml:/etc/athena/main.yaml
    command: /athena-processor --config /etc/athena/main.yaml --log.level="debug"
    depends_on:
      - nats-streaming
      - db
    networks:
      - athena
    restart: always

  nats-streaming:
    container_name: nats-streaming
    image: nats-streaming
    ports:
      - '4222:4222'
      - '8223:8223'
      - 4222
    environment:
      - file
    networks:
      - athena
    restart: always

networks:
  athena:
    driver: bridge