name: Publish to ghcr.io

on:
  release:
    types:
      - published

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-and-build:
    # Include the build workflow.
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_iduses
    uses: ./.github/workflows/test-and-build.yaml

  ghcr-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: test-and-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get packages
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata - processor
        id: processor_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/athena-processor

      - name: Build and publish Docker - processor
        id: processor-build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cmd/processor/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.processor_meta.outputs.tags }}
          labels: ${{ steps.processor_meta.outputs.labels }}

      - name: Extract Docker metadata - monitor
        id: monitor_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/athena-monitor

      - name: Build and publish Docker - monitor
        id: monitor_build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./cmd/monitor/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.monitor_meta.outputs.tags }}
          labels: ${{ steps.monitor_meta.outputs.labels }}
