on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Tests/Jobs for main branch merges
jobs:
  test:
    strategy:
      matrix:
        go-version: [ "1.22" ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test and Build
        run: make all
