name: Test and Build

on:
  schedule:
    - cron: '38 11 * * *'
  push:
    branches:
      - main
    tags:
      - 'v*.*.*' # v0.1.2
      - 'v2*-*'  # v20240613-1
  pull_request:
    branches:
      - main
  workflow_dispatch:
  # We will include this workflow in the ghcr-build-and-publish.yaml workflow.
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_call
  workflow_call:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Test and Build
        run: make all

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: build/*
